# Generated by Django 3.2.6 on 2021-10-20 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_topic', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 10, 20, 16, 2, 25, 485107, tzinfo=utc), verbose_name='date published')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 2, 25, 485107, tzinfo=utc), verbose_name='date end')),
                ('exam_duration', models.IntegerField(default=None)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUIZ.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUIZ.question')),
            ],
        ),
    ]
