# Generated by Django 3.2.6 on 2021-11-06 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 8, 58, 16, 880027, tzinfo=utc), verbose_name='date end'),
        ),
    ]
