# Generated by Django 3.2.7 on 2021-10-29 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 11, 13, 29, 279799, tzinfo=utc), verbose_name='date end'),
        ),
    ]
