# Generated by Django 3.2.6 on 2021-10-20 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 37, 48, 299363, tzinfo=utc), verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 16, 37, 48, 299363, tzinfo=utc), verbose_name='date published'),
        ),
    ]
