# Generated by Django 3.2.6 on 2021-11-06 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 6, 41, 3, 441466, tzinfo=utc), verbose_name='date end'),
        ),
    ]
