# Generated by Django 3.2.7 on 2021-10-23 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0002_auto_20211020_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 8, 41, 28, 573259, tzinfo=utc), verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 8, 41, 28, 573259, tzinfo=utc), verbose_name='date published'),
        ),
    ]
