# Generated by Django 3.2.7 on 2021-11-13 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0002_auto_20211113_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(default='0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 8, 28, 7, 253515, tzinfo=utc), verbose_name='date end'),
        ),
    ]
