# Generated by Django 3.2.7 on 2021-11-13 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0003_auto_20211113_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 8, 58, 5, 23471, tzinfo=utc), verbose_name='date end'),
        ),
    ]
