# Generated by Django 3.2.8 on 2021-10-30 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KUIZ', '0003_auto_20211030_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('', '----------'), ('programming', 'Programming'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('astronomy', 'Astronomy'), ('social', 'Social'), ('sport', 'Sport'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 47, 5, 146526, tzinfo=utc), verbose_name='date end'),
        ),
    ]
